"use client";

import React, { createContext, useContext } from 'react';
import { useChunk } from 'stunk/react';
import { languageChunk, Language } from '../lib/store';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
    EN: {
        hero_title: "Autonomous Motion Studio.",
        hero_subtitle: "Africa's Premier",
        hero_description: "Motion Pipe is a marketing automation infrastructure for high-velocity teams. Generate broadcast-ready motion graphics, product advertisements, and high-impact campaign graphics optimized to boost your social media engagement. Scale your creative output without scaling your headcount.",
        nav_capabilities: "Capabilities",
        nav_workflow: "Workflow",
        nav_pricing: "Pricing",
        nav_login: "Login",
        nav_get_started: "Get Started",
        how_it_works: "How it Works",
        start_project: "Start Project",
        view_demo: "View Demo",
        core_capabilities: "Core Capabilities",
        capabilities_desc: "Automated motion design infrastructure.",
        enterprise_stack: "Enterprise Stack",
        footer_tagline: "The automated motion design infrastructure for high-velocity marketing teams. Escrow-secured, AI-generated, broadcast-ready.",
        // Dashboard
        dash_home: "Dashboard",
        dash_assets: "Assets",
        dash_templates: "Templates",
        dash_history: "History",
        dash_billing: "Billing",
        dash_support: "Support",
        dash_settings: "Settings",
        dash_tickets: "Tickets",
        dash_profile: "Profile",
        // Dashboard Headers
        dash_workspace: "Workspace",
        dash_collaborate: "Collaborate",
        dash_finance: "Finance",
        dash_system: "System",
        dash_logout: "Log Out",
        invite_placeholder: "teammate@email.com",
        // Auth
        auth_back_home: "BACK TO HOME",
        auth_welcome: "Welcome Back",
        auth_access: "Access your creative workspace.",
        auth_join: "Join Motion Pipe",
        auth_journey: "Start your motion design journey.",
        auth_google: "Continue with Google",
        auth_x: "Continue with X",
        auth_terms: "By continuing, you agree to our Terms and Privacy Policy.",
        auth_no_account: "Don't have an account?",
        auth_signup: "Sign Up here",
        auth_has_account: "Already have an account?",
        auth_login: "Login here",
        // CTA
        cta_title: "Start Broadcasting.",
        cta_desc: "Join the agencies producing high-conversion ads without the studio costs.",
        cta_button: "Create Ad - ₦10,000",
        // Features
        feat_1_title: "AI Video Generation",
        feat_1_desc: "Advanced Generative Video models create stunning visual flows and animations.",
        feat_2_title: "Professional Voiceover",
        feat_2_desc: "Neural audio synthesis generates natural, broadcast-quality narration.",
        feat_3_title: "AI Sound Agent",
        feat_3_desc: "Curated licensed music and SFX, matched to mood.",
        feat_4_title: "Escrow Protection",
        feat_4_desc: "Funds only held. Released upon your approval.",
        feat_5_title: "Real-Time Updates",
        feat_5_desc: "WebSocket-powered live progress tracking.",
        feat_6_title: "Smart Asset Discovery",
        feat_6_desc: "Smart crawling agents find brand assets automatically.",
        // Tech
        tech_1: "High-Performance Backend",
        tech_2: "Next-Gen Video AI",
        tech_3: "Media Processing Engine",
        tech_4: "Global CDN",
        tech_5: "Secure Escrow",
        tech_6: "Real-Time Cache",
        // Pricing
        pricing_title: "Transparent",
        pricing_subtitle: "Pricing",
        pricing_desc: "No hidden fees. Pay for output.",
        pay_go: "Pay-As-You-Go",
        pay_go_desc: "For agencies & brands.",
        pay_go_price: "/ Video",
        enterprise: "Enterprise",
        enterprise_desc: "High volume infrastructure.",
        enterprise_price: "Custom",
        feat_4k: "4K Broadcast Quality",
        feat_voice: "AI Voiceover (ElevenLabs)",
        feat_watermark: "No Watermark",
        feat_gpu: "Dedicated GPU Instances",
        feat_models: "Custom Brand Models",
        feat_support: "Priority Support",
        btn_contact: "Contact Sales",
        // FAQ
        faq_title: "System FAQ",
        faq_1_q: "Escrow Protection Policy",
        faq_1_a: "Funds are held by Paystack Escrow. You inspect the video preview. Approve to release, or reject to get refunded minus a ₦1,000 compute fee.",
        faq_2_q: "Commercial Rights & Asset Usage",
        faq_2_a: "You own full rights to the generated video upon payment release. We use licensed stock music and cleared voiceovers.",
        faq_3_q: "Automated Asset Discovery",
        faq_3_a: "Our smart automated bot crawls your provided URL for logos and product shots. You can manually override these in the dashboard.",
        faq_4_q: "Average Generation Latency",
        faq_4_a: "Standard: 2-5 minutes. Priority (Creator Plan): <90 seconds. We use parallel processing nodes.",
        // Footer & Legal
        // Cookie Consent
        cookie_title: "Privacy & Cookies",
        cookie_text: "We use cookies to enhance your experience and analyze our traffic. By continuing, you agree to our terms.",
        cookie_accept: "Accept All",
        legal_title: "LEGAL",
        platform_title: "PLATFORM",
        rights_reserved: "MOTION PIPE SYSTEMS INC. ALL RIGHTS RESERVED.",
        status_online: "ALL SYSTEMS OPERATIONAL",
        status_degraded: "DEGRADED PERFORMANCE",
        status_offline: "SYSTEMS OFFLINE",
        link_terms: "Terms of Service",
        link_privacy: "Privacy Policy",
        link_escrow: "Escrow Agreement",
    },
    FR: {
        hero_title: "Studio de Mouvement Autonome.",
        hero_subtitle: "Le Premier en Afrique",
        hero_description: "Motion Pipe est une infrastructure d'automatisation marketing pour les équipes à haute vélocité. Générez des graphismes animés prêts à diffuser, des publicités produits et des visuels de campagne à fort impact optimisés pour booster votre engagement social. Échellez votre production créative sans augmenter vos effectifs.",
        nav_capabilities: "Capacités",
        nav_workflow: "Flux de travail",
        nav_pricing: "Tarification",
        nav_login: "Connexion",
        nav_get_started: "Commencer",
        how_it_works: "Comment ça marche",
        start_project: "Lancer le projet",
        view_demo: "Voir la démo",
        core_capabilities: "Capacités de base",
        capabilities_desc: "Infrastructure de conception de mouvement automatisée.",
        enterprise_stack: "Pile d'Entreprise",
        footer_tagline: "L'infrastructure de conception de mouvement automatisée pour les équipes marketing à haute vélocité. Sécurisé par séquestre, généré par IA, prêt pour la diffusion.",
        dash_home: "Tableau de Bord",
        dash_assets: "Ressources",
        dash_templates: "Modèles",
        dash_history: "Historique",
        dash_billing: "Facturation",
        dash_support: "Support",
        dash_settings: "Paramètres",
        dash_tickets: "Tickets",
        dash_profile: "Profil",
        // Dashboard Headers
        dash_workspace: "Espace de Travail",
        dash_collaborate: "Collaborer",
        dash_finance: "Finance",
        dash_system: "Système",
        dash_logout: "Déconnexion",
        invite_placeholder: "collegue@email.com",
        // Auth
        auth_back_home: "RETOUR À L'ACCUEIL",
        auth_welcome: "Bon retour",
        auth_access: "Accédez à votre espace créatif.",
        auth_join: "Rejoignez Motion Pipe",
        auth_journey: "Commencez votre voyage en motion design.",
        auth_google: "Continuer avec Google",
        auth_x: "Continuer avec X",
        auth_terms: "En continuant, vous acceptez nos CGU et Politique de Confidentialité.",
        auth_no_account: "Pas de compte ?",
        auth_signup: "Inscrivez-vous ici",
        auth_has_account: "Déjà un compte ?",
        auth_login: "Connectez-vous ici",
        // CTA
        cta_title: "Commencez la diffusion.",
        cta_desc: "Rejoignez les agences produisant des publicités à haute conversion sans les coûts de studio.",
        cta_button: "Créer une publicité - ₦10 000",
        // Features
        feat_1_title: "Génération de Vidéo IA",
        feat_1_desc: "L'IA vidéo avancée crée des flux visuels et des animations époustouflants.",
        feat_2_title: "Voix-off Professionnelle",
        feat_2_desc: "La synthèse vocale neurale génère une narration naturelle et de qualité diffusion.",
        feat_3_title: "Agent Sonore IA",
        feat_3_desc: "Musique sous licence et SFX sélectionnés, adaptés à l'ambiance.",
        feat_4_title: "Protection par Séquestre",
        feat_4_desc: "Les fonds sont conservés et libérés uniquement après votre approbation.",
        feat_5_title: "Mises à jour en Temps Réel",
        feat_5_desc: "Suivi en direct de la progression via WebSocket.",
        feat_6_title: "Découverte Intelligente des Ressources",
        feat_6_desc: "Des agents intelligents trouvent automatiquement les ressources de la marque.",
        // Tech
        tech_1: "Backend Haute Performance",
        tech_2: "Vidéo IA Nouvelle Gen",
        tech_3: "Moteur de Traitement Média",
        tech_4: "CDN Mondial",
        tech_5: "Séquestre Sécurisé",
        tech_6: "Cache Temps Réel",
        // Pricing
        pricing_title: "Transparente",
        pricing_subtitle: "Tarification",
        pricing_desc: "Pas de frais cachés. Payez pour le résultat.",
        pay_go: "Payez à l'usage",
        pay_go_desc: "Pour agences & marques.",
        pay_go_price: "/ Vidéo",
        enterprise: "Entreprise",
        enterprise_desc: "Infrastructure à gros volume.",
        enterprise_price: "Sur mesure",
        feat_4k: "Qualité Diffusion 4K",
        feat_voice: "Voix-off IA (Synthèse Neurale)",
        feat_watermark: "Pas de filigrane",
        feat_gpu: "Instances GPU Dediées",
        feat_models: "Modèles de Marque Personnalisés",
        feat_support: "Support Prioritaire",
        btn_contact: "Contacter les Ventes",
        // FAQ
        faq_title: "FAQ Système",
        faq_1_q: "Politique de Protection par Séquestre",
        faq_1_a: "Les fonds sont détenus par Paystack Escrow. Vous inspectez l'aperçu vidéo. Approuvez pour libérer, ou rejetez pour être remboursé moins ₦1 000 de frais de calcul.",
        faq_2_q: "Droits Commerciaux & Utilisation des Ressources",
        faq_2_a: "Vous possédez tous les droits sur la vidéo générée après libération du paiement. Nous utilisons de la musique sous licence et des voix libres de droits.",
        faq_3_q: "Découverte Automatisée des Ressources",
        faq_3_a: "Notre bot automatisé parcourt votre URL pour trouver logos et images produits. Vous pouvez les modifier manuellement dans le tableau de bord.",
        faq_4_q: "Latence Moyenne de Génération",
        faq_4_a: "Standard : 2-5 minutes. Priorité (Plan Créateur) : <90 secondes. Nous utilisons des nœuds de traitement parallèle.",
        // Footer & Legal
        // Cookie Consent
        cookie_title: "Confidentialité & Cookies",
        cookie_text: "Nous utilisons des cookies pour améliorer votre expérience. En continuant, vous acceptez nos conditions.",
        cookie_accept: "Tout Accepter",
        legal_title: "JURIDIQUE",
        platform_title: "PLATEFORME",
        rights_reserved: "MOTION PIPE SYSTEMS INC. TOUS DROITS RÉSERVÉS.",
        status_online: "TOUS LES SYSTÈMES OPÉRATIONNELS",
        status_degraded: "PERFORMANCE DÉGRADÉE",
        status_offline: "SYSTÈMES HORS LIGNE",
        link_terms: "Conditions d'Utilisation",
        link_privacy: "Politique de Confidentialité",
        link_escrow: "Accord de Séquestre",
    },
    ES: {
        hero_title: "Estudio de Movimiento Autónomo.",
        hero_subtitle: "El Principal de África",
        hero_description: "Motion Pipe es una infraestructura de automatización de marketing para equipos de alta velocidad. Genere gráficos en movimiento listos para transmisión, anuncios de productos e imágenes de campaña de alto impacto optimizadas para aumentar su participación en redes sociales. Escale su producción creativa sin aumentar su personal.",
        nav_capabilities: "Capacidades",
        nav_workflow: "Flujo de trabajo",
        nav_pricing: "Precios",
        nav_login: "Acceso",
        nav_get_started: "Empezar",
        how_it_works: "Cómo funciona",
        start_project: "Iniciar Proyecto",
        view_demo: "Ver Demo",
        core_capabilities: "Capacidades Principales",
        capabilities_desc: "Infraestructura de diseño de movimiento automatizada.",
        enterprise_stack: "Pila Empresarial",
        footer_tagline: "La infraestructura de diseño de movimiento automatizada para equipos de marketing de alta velocidad. Depósito en garantía asegurado, generado por IA, listo para la emisión.",
        dash_home: "Panel",
        dash_assets: "Activos",
        dash_templates: "Plantillas",
        dash_history: "Historial",
        dash_billing: "Facturación",
        dash_support: "Soporte",
        dash_settings: "Configuración",
        dash_tickets: "Tickets",
        dash_profile: "Perfil",
        // Dashboard Headers
        dash_workspace: "Espacio de Trabajo",
        dash_collaborate: "Colaborar",
        dash_finance: "Finanzas",
        dash_system: "Sistema",
        dash_logout: "Cerrar Sesión",
        invite_placeholder: "colega@email.com",
        // Auth
        auth_back_home: "VOLVER AL INICIO",
        auth_welcome: "Bienvenido de nuevo",
        auth_access: "Accede a tu espacio creativo.",
        auth_join: "Únete a Motion Pipe",
        auth_journey: "Comienza tu viaje en diseño de movimiento.",
        auth_google: "Continuar con Google",
        auth_x: "Continuar con X",
        auth_terms: "Al continuar, aceptas nuestros Términos y Política de Privacidad.",
        auth_no_account: "¿No tienes cuenta?",
        auth_signup: "Regístrate aquí",
        auth_has_account: "¿Ya tienes cuenta?",
        auth_login: "Inicia sesión aquí",
        // CTA
        cta_title: "Empieza a Emitir.",
        cta_desc: "Únete a las agencias que producen anuncios de alta conversión sin los costos de estudio.",
        cta_button: "Crear Anuncio - ₦10,000",
        // Features
        feat_1_title: "Generación de Video IA",
        feat_1_desc: "La IA de video avanzada crea flujos visuales y animaciones impresionantes.",
        feat_2_title: "Locución Profesional",
        feat_2_desc: "La síntesis de audio neural genera una narración natural y de calidad profesional.",
        feat_3_title: "Agente de Sonido IA",
        feat_3_desc: "Música licenciada y efectos de sonido seleccionados, adaptados al ambiente.",
        feat_4_title: "Protección de Depósito en Garantía",
        feat_4_desc: "Los fondos solo se retienen y se liberan tras tu aprobación.",
        feat_5_title: "Actualizaciones en Tiempo Real",
        feat_5_desc: "Seguimiento en vivo del progreso impulsado por WebSocket.",
        feat_6_title: "Descubrimiento Inteligente de Activos",
        feat_6_desc: "Agentes inteligentes encuentran activos de marca automáticamente.",
        // Tech
        tech_1: "Backend de Alto Rendimiento",
        tech_2: "IA de Video Next-Gen",
        tech_3: "Motor de Procesamiento de Medios",
        tech_4: "CDN Global",
        tech_5: "Depósito Seguro",
        tech_6: "Caché en Tiempo Real",
        // Pricing
        pricing_title: "Precios",
        pricing_subtitle: "Transparentes",
        pricing_desc: "Sin tarifas ocultas. Paga por resultado.",
        pay_go: "Pago por Uso",
        pay_go_desc: "Para agencias y marcas.",
        pay_go_price: "/ Video",
        enterprise: "Empresarial",
        enterprise_desc: "Infraestructura de alto volumen.",
        enterprise_price: "A medida",
        feat_4k: "Calidad de Emisión 4K",
        feat_voice: "Locución IA (Síntesis Neurale)",
        feat_watermark: "Sin Marca de Agua",
        feat_gpu: "Instancias GPU Dedicadas",
        feat_models: "Modelos de Marca Personalizados",
        feat_support: "Soporte Prioritario",
        btn_contact: "Contactar Ventas",
        // FAQ
        faq_title: "Preguntas Frecuentes del Sistema",
        faq_1_q: "Política de Protección de Depósito en Garantía",
        faq_1_a: "Los fondos son retenidos por Paystack Escrow. Inspeccionas la vista previa del video. Aprueba para liberar, o rechaza para obtener un reembolso menos una tarifa de cómputo de ₦1,000.",
        faq_2_q: "Derechos Comerciales y Uso de Activos",
        faq_2_a: "Posees todos los derechos del video generado tras la liberación del pago. Usamos música de stock con licencia y locuciones autorizadas.",
        faq_3_q: "Descubrimiento Automatizado de Activos",
        faq_3_a: "Nuestro bot automatizado rastrea tu URL proporcionada en busca de logotipos y fotos de productos. Puedes anularlos manualmente en el panel.",
        faq_4_q: "Latencia Promedio de Generación",
        faq_4_a: "Estándar: 2-5 minutos. Prioridad (Plan Creador): <90 segundos. Usamos nodos de procesamiento paralelo.",
        // Footer & Legal
        // Cookie Consent
        cookie_title: "Privacidad y Cookies",
        cookie_text: "Utilizamos cookies para mejorar su experiencia. Al continuar, acepta nuestros términos.",
        cookie_accept: "Aceptar Todo",
        legal_title: "LEGAL",
        platform_title: "PLATAFORMA",
        rights_reserved: "MOTION PIPE SYSTEMS INC. TODOS LOS DERECHOS RESERVADOS.",
        status_online: "TODOS LOS SISTEMAS OPERATIVOS",
        status_degraded: "RENDIMIENTO DEGRADADO",
        status_offline: "SISTEMAS FUERA DE LÍNEA",
        link_terms: "Términos de Servicio",
        link_privacy: "Política de Privacidad",
        link_escrow: "Acuerdo de Depósito",
    },
    DE: {
        hero_title: "Autonomes Motion Studio.",
        hero_subtitle: "Afrikas Führender",
        hero_description: "Motion Pipe ist eine Marketing-Automatisierungsinfrastruktur für Hochgeschwindigkeits-Teams. Generieren Sie sendebereite Motion Graphics, Produktwerbungen und wirkungsvolle Kampagnengrafiken, die für mehr Social-Media-Engagement optimiert sind. Skalieren Sie Ihren kreativen Output ohne zusätzliches Personal.",
        nav_capabilities: "Funktionen",
        nav_workflow: "Arbeitsablauf",
        nav_pricing: "Preise",
        nav_login: "Login",
        nav_get_started: "Loslegen",
        how_it_works: "So funktioniert es",
        start_project: "Projekt starten",
        view_demo: "Demo ansehen",
        core_capabilities: "Kernfunktionen",
        capabilities_desc: "Automatisierte Motion-Design-Infrastruktur.",
        enterprise_stack: "Enterprise-Stack",
        footer_tagline: "Die automatisierte Motion-Design-Infrastruktur für hochfrequente Marketingteams. Treuhandgesichert, KI-generiert, sendefertig.",
        dash_home: "Dashboard",
        dash_assets: "Assets",
        dash_templates: "Vorlagen",
        dash_history: "Verlauf",
        dash_billing: "Abrechnung",
        dash_support: "Support",
        dash_settings: "Einstellungen",
        dash_tickets: "Tickets",
        dash_profile: "Profil",
        // Dashboard Headers
        dash_workspace: "Arbeitsbereich",
        dash_collaborate: "Zusammenarbeiten",
        dash_finance: "Finanzen",
        dash_system: "System",
        dash_logout: "Abmelden",
        invite_placeholder: "kollege@email.com",
        // Auth
        auth_back_home: "ZURÜCK ZUM START",
        auth_welcome: "Willkommen zurück",
        auth_access: "Greifen Sie auf Ihren kreativen Bereich zu.",
        auth_join: "Treten Sie Motion Pipe bei",
        auth_journey: "Beginnen Sie Ihre Motion-Design-Reise.",
        auth_google: "Weiter mit Google",
        auth_x: "Weiter mit X",
        auth_terms: "Durch Fortfahren akzeptieren Sie unsere AGB und Datenschutzrichtlinie.",
        auth_no_account: "Kein Konto?",
        auth_signup: "Hier registrieren",
        auth_has_account: "Bereits ein Konto?",
        auth_login: "Hier anmelden",
        // CTA
        cta_title: "Starten Sie die Übertragung.",
        cta_desc: "Schließen Sie sich den Agenturen an, die hochkonvertierende Anzeigen ohne Studiokosten produzieren.",
        cta_button: "Anzeige erstellen - ₦10.000",
        // Features
        feat_1_title: "KI-Videogenerierung",
        feat_1_desc: "Fortschrittliche Video-KI erstellt atemberaubende visuelle Abläufe und Animationen.",
        feat_2_title: "Professionelles Voiceover",
        feat_2_desc: "Neurale Audiosynthese generiert natürliche Erzählungen in Sendequalität.",
        feat_3_title: "KI-Sound-Agent",
        feat_3_desc: "Kuratierte lizenzierte Musik und SFX, passend zur Stimmung.",
        feat_4_title: "Treuhandschutz",
        feat_4_desc: "Mittel werden nur einbehalten und bei Ihrer Genehmigung freigegeben.",
        feat_5_title: "Echtzeit-Updates",
        feat_5_desc: "WebSocket-gestütztes Live-Fortschritts-Tracking.",
        feat_6_title: "Intelligente Asset-Suche",
        feat_6_desc: "Intelligente Agenten finden Marken-Assets automatisch.",
        // Tech
        tech_1: "Hochleistungs-Backend",
        tech_2: "Next-Gen Video-KI",
        tech_3: "Medienverarbeitungs-Engine",
        tech_4: "Globales CDN",
        tech_5: "Sicherer Treuhandservice",
        tech_6: "Echtzeit-Cache",
        // Pricing
        pricing_title: "Transparente",
        pricing_subtitle: "Preise",
        pricing_desc: "Keine versteckten Gebühren. Zahlen Sie für Ergebnisse.",
        pay_go: "Pay-As-You-Go",
        pay_go_desc: "Für Agenturen & Marken.",
        pay_go_price: "/ Video",
        enterprise: "Enterprise",
        enterprise_desc: "Hochvolumige Infrastruktur.",
        enterprise_price: "Individuell",
        feat_4k: "4K Sendequalität",
        feat_voice: "KI-Voiceover (Neurale Synthese)",
        feat_watermark: "Kein Wasserzeichen",
        feat_gpu: "Dedizierte GPU-Instanzen",
        feat_models: "Individuelle Markenmodelle",
        feat_support: "Priorisierter Support",
        btn_contact: "Vertrieb kontaktieren",
        // FAQ
        faq_title: "System-FAQ",
        faq_1_q: "Treuhand-Schutzrichtlinie",
        faq_1_a: "Gelder werden von Paystack Escrow gehalten. Sie prüfen die Videovorschau. Genehmigen Sie die Freigabe oder lehnen Sie ab, um eine Rückerstattung abzüglich einer Rechengebühr von ₦1.000 zu erhalten.",
        faq_2_q: "Kommerzielle Rechte & Asset-Nutzung",
        faq_2_a: "Sie besitzen nach Zahlungsfreigabe alle Rechte am generierten Video. Wir verwenden lizensierte Stockmusik und geklärte Voiceovers.",
        faq_3_q: "Automatisierte Asset-Suche",
        faq_3_a: "Unser automatisierter Bot durchsucht Ihre angegebene URL nach Logos und Produktfotos. Sie können diese im Dashboard manuell überschreiben.",
        faq_4_q: "Durchschnittliche Generierungslatenz",
        faq_4_a: "Standard: 2-5 Minuten. Priorität (Creator-Plan): <90 Sekunden. Wir verwenden parallele Serverknoten.",
        // Footer & Legal
        // Cookie Consent
        cookie_title: "Datenschutz & Cookies",
        cookie_text: "Wir verwenden Cookies, um Ihre Erfahrung zu verbessern. Wenn Sie fortfahren, stimmen Sie unseren Bedingungen zu.",
        cookie_accept: "Alle Akzeptieren",
        legal_title: "RECHTLICHES",
        platform_title: "PLATTFORM",
        rights_reserved: "MOTION PIPE SYSTEMS INC. ALLE RECHTE VORBEHALTEN.",
        status_online: "ALLE SYSTEME BETRIEBSBEREIT",
        status_degraded: "EINGESCHRÄNKTE LEISTUNG",
        status_offline: "SYSTEME OFFLINE",
        link_terms: "Nutzungsbedingungen",
        link_privacy: "Datenschutzerklärung",
        link_escrow: "Treuhandvereinbarung",
    }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [language, setLanguage] = useChunk(languageChunk);

    const t = (key: string) => {
        return translations[language as Language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
}
